### PR TITLE
Allow safe decompression inside vehicles (configurable)

### PR DESCRIPTION
**Pull request by joker-119**
We're not talking about that last PR.

This ones done correctly, no game assemblies included.

Adds enable-able safe-decompression options while inside vehicles, it makes no sense for the submersible to be 1atm while still allowing people to enter/exit the vehicle at extreme depths. These vehicles would need an internal pressure equivalent to the exterior in order to allow this, and thus would also be capable of slowly decompressing the atmosphere inside to allow safe decompression without health risks.

### CODE REVIEW

**Comment by joker-119** [comment]
Also yes I'm aware there's alot of styling changes that are irrelevant, I can revert these if necessary, Jetbrains did them all automatically when I pushed to the fork, they weren't done intentionally, just let me know if you would like me to do it.

**Comment by seraphimrisen** [comment]
Yeah, I'm looking it over right now. Some of them are odd since using "ex" is not the same as "ex.ToString()". I'll review it all - I'd prefer the style changes reverted, if possible, because it helps me read the code. I realize those are superfluous, but it'd help me find the specific relevant changes if those can be reverted. For now I'll keep looking it over since I have some time, even though I can't actually get to the computer and work on the code.

**Comment by joker-119** [comment]
Normally yes, but when adding ex to a string it implicitly casts it as a string, which means ex.ToString() is redundant, since you're basically calling .ToString() on a string.
I can go through and revert the property and using changes sure. I'll keep in the references changes and such, i'll just get rid of everything that isn't functional changes.

**Comment by seraphimrisen** [comment]
Okay, that makes sense then.I will definitely take the reference changes
and fix all that up so it's easier to use. I didn't realize it was a
problem.

**Comment by joker-119** [comment]
Would you like me to just add a new commit reverting the non-functional changes, or do you want me to re-write the commit and submit a new PR so you only see the functional changes?

**Comment by joker-119** [comment]
Also I wouldn't classify the references as a *problem* so much a *extreme inconvenience* Thankfully I already had most of the references set aside from my own projects I'd been tinkering with, but to someone who's completely new to subnautica modding, wether they have experiance programming or not, having references in the repo helps alot. 

It also prevents people from using the wrong, or outdated references then whining about the project not building properly.

If you look at my repos fro SCPSL server plugins, you'll see I include all refs needed to build, including assmeblies (SCP:SL is published under CreativeCommons Share-Alike so there's no legal issues or anything in those examples).

**Comment by seraphimrisen** [comment]
I'll definitely get that fixed when I can. I was expecting to work on it
today and then work handed me a 13-hour shift

**Comment by seraphimrisen** [comment]
Feature has been implemented, as well as mod brought up to date with Unity 2018.2

**Pull request closed without merging**
